apiVersion: v2
name: openshift-cacheclear
description: Scheduled cache clearing for OpenShift cluster nodes
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - openshift
  - cache
  - maintenance
  - cronjob
  - node-management
home: https://github.com/slauger/helm-charts
sources:
  - https://github.com/slauger/helm-charts
maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
