apiVersion: v2
name: deployment-simple
description: Simple Kubernetes deployment chart with minimal configuration
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - deployment
  - simple
  - kubernetes
home: https://github.com/slauger/helm-charts
sources:
  - https://github.com/slauger/helm-charts
maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
