apiVersion: v2
name: openshift-ldap-sync
description: Automated LDAP/Active Directory group synchronization for OpenShift
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - openshift
  - ldap
  - active-directory
  - authentication
  - rbac
  - cronjob
home: https://github.com/slauger/helm-charts
sources:
  - https://github.com/slauger/helm-charts
maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
