apiVersion: v2
name: deployment
description: Kubernetes deployment chart with Envoy proxy sidecar for TLS termination
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - deployment
  - envoy
  - proxy
  - tls
  - kubernetes
home: https://github.com/slauger/helm-charts
sources:
  - https://github.com/slauger/helm-charts
maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
