apiVersion: v2
name: example-chart
description: Example Helm chart demonstrating common Kubernetes deployment patterns
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - example
  - template
  - nginx
  - deployment
  - kubernetes
home: https://github.com/slauger/helm-charts
sources:
  - https://github.com/slauger/helm-charts
maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
