{{- if .Values.auth.htpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-registry.fullname" . }}-auth
  labels:
    {{- include "hcloud-registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ .Values.auth.htpasswd }}
{{- end }}
