{{- if and .Values.storage.s3.accessKey .Values.storage.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-registry.fullname" . }}-s3
  labels:
    {{- include "hcloud-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.storage.s3.accessKey | quote }}
  secretKey: {{ .Values.storage.s3.secretKey | quote }}
{{- end }}
